**Операции с матрицами**


In [1]:
import numpy as np
import sympy as sp

***Сложение матриц***

In [2]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

C = A + B
print(C)

D = np.add(A, B)
print(D)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [3]:
A = sp.Matrix([[1, 2], 
               [3, 4]])
B = sp.Matrix([[5, 6], 
               [7, 8]])

C = A + B
print(C)

Matrix([[6, 8], [10, 12]])


**Вычитание матриц**

In [4]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

C = A - B
print(C)

[[-4 -4]
 [-4 -4]]


In [5]:
A = sp.Matrix([[1, 2], 
               [3, 4]])
B = sp.Matrix([[5, 6], 
               [7, 8]])

C = A - B
print(C)

Matrix([[-4, -4], [-4, -4]])


**Умножение на константу**

In [6]:
A = np.array([[1, 2], 
              [3, 4]])
k = 2

C = k * A
print(C)

D = np.multiply(k, A)
print(D)

[[2 4]
 [6 8]]
[[2 4]
 [6 8]]


In [7]:
A = sp.Matrix([[1, 2], 
               [3, 4]])
k = 2

C = A.multiply(k)
print(C)

Matrix([[2, 4], [6, 8]])


**Умножение матрицы на матрицу**

In [8]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

C = np.dot(A, B)
print(C)

D = A @ B
print(D)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [9]:
A = sp.Matrix([[1, 2], 
               [3, 4]])
B = sp.Matrix([[5, 6], 
               [7, 8]])

C = A * B
print(C)

Matrix([[19, 22], [43, 50]])


***Транспонирование матрицы***

In [10]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

C = np.transpose(A)
print(C)

D = A.T
print(D)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [11]:
A = sp.Matrix([[1, 2], 
               [3, 4], 
               [5, 6]])

C = A.transpose()
print(C)

D = A.T
print(D)

Matrix([[1, 3, 5], [2, 4, 6]])
Matrix([[1, 3, 5], [2, 4, 6]])


***Использование единичной и обратной матрицы***

In [12]:
# Единичная матрица
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
A = np.array([[1, 2], 
              [3, 4]])

# Обратная матрица
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
# Единичная матрица
I = sp.eye(3)
print(I)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [15]:
A = sp.Matrix([[1, 2], 
               [3, 4]])

# Обратная матрица
A_inv = A.inv()
print(A_inv)

Matrix([[-2, 1], [3/2, -1/2]])


***Ранг матрицы***

In [16]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисление ранга матрицы
rank = np.linalg.matrix_rank(matrix)
print(rank)

2


In [17]:
matrix = sp.Matrix([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Вычисление ранга матрицы
rank = matrix.rank()
print(rank)

2


***Определитель матрицы***

In [18]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Вычисление определителя матрицы
det_A = np.linalg.det(A)
print(det_A)


0.0


In [19]:
A = sp.Matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Вычисление определителя матрицы
det_A = A.det()
print(det_A)

0
