**Операции с векторами**


In [1]:
import numpy as np
import sympy as sp

***Вычисление длины вектора***

In [2]:
v = np.array([2, 3, 4])

length = np.linalg.norm(v) # по умолчанию вычисляется L2 или евклидова норма
print(length)

length = np.linalg.norm(v, ord=1) # вычисляется L1 или манхеттенская норма
print(length)

length = np.linalg.norm(v, ord=3) # вычисляется L3 или кубическая норма
print(length)

5.385164807134504
9.0
4.626065009182741


***Сложение векторов***

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

v_sum = v1 + v2
print(v_sum)

[5 7 9]


In [4]:
v1 = sp.Matrix([1, 2, 3])
v2 = sp.Matrix([4, 5, 6])

v_sum = v1 + v2
print(v_sum)

Matrix([[5], [7], [9]])


**Вычитание векторов**

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

v_sum = v1 - v2
print(v_sum)

[-3 -3 -3]


In [6]:
v1 = sp.Matrix([1, 2, 3])
v2 = sp.Matrix([4, 5, 6])

v_diff = v1 - v2
print(v_diff)

Matrix([[-3], [-3], [-3]])


**Умножение на константу**

In [7]:
a = np.array([1, 2, 3])
k = 2

b = k * a
print(b)

[2 4 6]


In [8]:
a = sp.Matrix([1, 2, 3])
k = 2

b = k * a
print(b)

Matrix([[2], [4], [6]])


**Скалярное призведение векторов**

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Вычисление скалярного произведения с помощью функции np.dot
dot_product = np.dot(a, b)
print(dot_product)

# Вычисление скалярного произведения с помощью метода .dot()
dot_product = a.dot(b)
print(dot_product)

32
32


In [10]:
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])

dot_product = a.dot(b)
print(dot_product)

32


***Векторное произведение векторов***

In [11]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Вычисление векторного произведения
v_cross = np.cross(v1, v2)
print(v_cross)

[-3  6 -3]


In [12]:
from sympy.vector import CoordSys3D, cross
N = CoordSys3D('N') # Создание трехмерной декартовой системы координат

# Определение двух векторов
v1 = 1*N.i + 2*N.j + 3*N.k
v2 = 4*N.i + 5*N.j + 6*N.k

v_cross = cross(v1, v2)
print(v_cross)

(-3)*N.i + 6*N.j + (-3)*N.k


***Вычисление расстояния между векторами***

In [13]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Вычисление расстояние между векторами по норме L2
distance = np.linalg.norm(v2 - v1)
print(distance)

# Вычисление расстояние между векторами по норме L1
distance = np.linalg.norm(v2 - v1, ord=1)
print(distance)

5.196152422706632
9.0


In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Вычисление косинусного расстояния
cosine_distance = 1 - np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
print(cosine_distance)

from scipy.spatial import distance
cosine_distance = distance.cosine(x, y)

print(cosine_distance)

0.025368153802923787
0.025368153802923787


In [15]:
a = sp.Matrix([1, 2, 3])
b = sp.Matrix([4, 5, 6])

# Вычисление расстояние между векторами по норме L2
distance = (a - b).norm()
print(distance)
print(distance.evalf())

# Вычисление расстояние между векторами по норме L1
distance = (a - b).norm(ord=1)
print(distance.evalf())

3*sqrt(3)
5.19615242270663
9.00000000000000
